### ISSUE TITLE
【体验相关】账户登出建议放在个人资料

### ISSUE THREAD

**Issue by pphaolu** [fox-one/Issues#10]
账户登出建议放在个人资料，而不是在首选项。一般首选项只是做功能，参数等等修改的。
而账户登出在个人资料页面比较合适，建议放2个按钮
1, 登出账户
2. 切换账户

**Comment by lyricat** [comment]
这里需要考虑一下。这两个页面的定位刚好差异很大：登出和切换属于帐号（account），而不属于 个人资料（profile）。

以 twitter 和 facebook 为例，二者的 profile 页面都不会放置跟 帐号（account）相关的操作；二者都有独立的 settings 页面（https://www.facebook.com/settings 和 https://twitter.com/settings/account）；二者的 settings 里都有跟 account 相关的操作。

当然了，二者的网页版 logout 不在 profile，也不在 settings。但是，他们的 App 里，logout 是在 settings 里面的。所以综合考虑，还是放在 settings 更合适。
