### ISSUE TITLE
交易所界面的 垂直滚动条 太难控制了

### ISSUE THREAD

**Issue by Zegele** [fox-one/Issues#20]
1.在fox打开某个交易所
2.点击“返回”键，让交易所全屏显示。
第三步出现bug
3.点击左上角头像，这时会被交易所页面遮挡。
![_20180506103527](https://user-images.githubusercontent.com/32725134/39669273-c7905422-5119-11e8-939a-1c01fb9cd686.png)

1.6版
168491

**Comment by lyricat** [comment]
Duplicate of #19
