### ISSUE TITLE
简体中文与繁体中文混合出现

### ISSUE THREAD

**Issue by wu60287** [fox-one/Issues#23]
> **影响:** 文字显示部份会有简中与繁中同时出现情形
![wechat _20180515103831](https://user-images.githubusercontent.com/38682043/40033722-3d72eca4-582c-11e8-8470-7773e2cdaed5.png)

>
> **客户端版本:** 1.6.1
>
> **客户端操作系统:** Windows
>
> **重现方法:** 
>
> 1. 程式仅部份地方会呈现

**Comment by lyricat** [comment]
Fixed in 1.6.5
