### ISSUE TITLE
防毒软体阻挡Foxone

### ISSUE THREAD

**Issue by wu60287** [fox-one/Issues#25]
影响 : Foxone开启时或执行过程中，防毒软体会阻挡，病会自动Foxone卸载
![wechat _20180515105027](https://user-images.githubusercontent.com/38682043/40034071-cfa1031c-582d-11e8-835a-c472de38e755.png)

客戶端版本：1.6.1
客戶端操作系統：Windows
重現方法：啟動Foxone

**Comment by lyricat** [comment]
等 Windows 加上证书后就行了。现在解决不了，只能让设置杀软忽略 FoxOne
