### ISSUE TITLE
注册时，任一字母的首选项无法被选择

### ISSUE THREAD

**Issue by wu60287** [fox-one/Issues#26]
问题 : 注册选择地区时，字母第一个选项无法被选择
![video-1526956725](https://user-images.githubusercontent.com/38682043/40340378-42515c6c-5db1-11e8-8c76-eb06d5bb9af5.gif)

客戶端版本：官网注册页
客戶端操作系統：Windows
重現方法：--

**Comment by lyricat** [comment]
已提交到内部 issue list
