### ISSUE TITLE
行情标签下，搜索币种，比如poe，点击 poe ，左边币种会自动跳会全体代币

### ISSUE THREAD

**Issue by kiwin007** [fox-one/Issues#7]
![_20180419163156](https://user-images.githubusercontent.com/38522913/38980514-9cccff06-43ef-11e8-98e6-318a13f15469.png)
当搜索poe/btc，点击  

![_20180419163313](https://user-images.githubusercontent.com/38522913/38980558-b74f8b8c-43ef-11e8-9e4b-ff3010ad5e58.png)
区域1自动跳会全体币种，

**Comment by lyricat** [comment]
confirmed

**Comment by lyricat** [comment]
Fixed in 1.5.4
