### ISSUE TITLE
数据-加密货币市场资本-排序filter未显示

### ISSUE THREAD

**Issue by Echo00** [fox-one/Issues#9]
- 用户ID：170924
- ![image](https://user-images.githubusercontent.com/38432206/39096492-6292caf0-4683-11e8-9d63-fc76c2e8db14.png)
![image](https://user-images.githubusercontent.com/38432206/39096495-6a0a6ef0-4683-11e8-9164-c23cb7ecbe09.png)
- bug出现时间：4.19 4:05pm
- windows

**Comment by lyricat** [comment]
Fixed in 1.6.0
